fig=imread('C:\Users\Administrator\Desktop\博客图片\阈值分割测试图片\wchatgame1.jpg');
figgray=rgb2gray(fig);
[IDX,sep] = otsu(fig);
CM=zeros(size(figgray));
CM(IDX==2)=1;
figure,imshow(CM);title(['Ostu阈值分割方法']);
T_O=Cluster_treshold(double(figgray),'Method','Cluster_Ostu');
CM=zeros(size(figgray));CM(figgray>T_O)=1;
figure,imshow(CM);title(['Ostu阈值分割方法']);
% 
T_K=Cluster_treshold(reshape(double(figgray),[],1),'Method','Cluster_Kittler');
CM=zeros(size(figgray));CM(figgray>T_K)=1;
figure,imshow(CM);title(['Cluster_Kittler分割方法']);
% 
T_EM=Cluster_treshold(reshape(double(figgray),[],1),'Method','Cluster_EM');
CM=zeros(size(figgray));CM(figgray>T_EM)=1;
figure,imshow(CM);title(['EM_CD分割方法']);
% 
T_fuzzy=Cluster_treshold(reshape(double(figgray),[],1));
CM=zeros(size(figgray));CM(figgray>T_fuzzy)=1;
figure,imshow(CM);title(['Cluster_Jawahar1分割方法']);
% 
T_fuzzy2=Cluster_treshold(reshape(double(figgray),[],1),'Method','Cluster_Jawahar1');
CM=zeros(size(figgray));CM(figgray>T_fuzzy2)=1;
figure,imshow(CM);title(['Cluster_Jawahar2分割方法']);
% 
T_L=Cluster_treshold(reshape(double(figgray),[],1),'Method','Cluster_Lloyd');
CM=zeros(size(figgray));CM(figgray>T_L)=1;
figure,imshow(CM);title(['Cluster_Lloyd分割方法']);
% 
